# This is a basic workflow to help you get started with Actions

name: Build LingmoOS amd64

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie-slim

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update repository
        run: apt-get update -y
      - name: Upgrade packages
        run: apt-get upgrade -y
      - name: Install the basic dev packages
        run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
      # Runs a single command using the runners shell
      - name: Run a build script
        run: echo 29 | bash build-github.sh

      - name: Zip built files
        run: tar -zcvf BuiltDeb.tar.gz ./LingmoSrcBuild/Deb

      - uses: actions/upload-artifact@v4
        with:
          name: LingmoOS amd64 Built
          path: BuiltDeb.tar.gz
          compression-level: 9 # maximum compression

      - uses: ncipollo/release-action@4f8867fa5eec0b3f59ead8f69aeba316c24907b3
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          prerelease: true
          name: "LingmoOS Development Build amd64"
          artifacts: "BuiltDeb.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

