name: Build LingmoOS Arm64

on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie-slim
    steps:   
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        
        - name: Add arm64 architecture
          run: |
            dpkg --add-architecture arm64
            apt update

        - name: Run a build script
          run: |
            echo 29 | bash build-github-cross-compile.sh

        - name: Zip built files
          run: tar -zcvf BuiltDeb.tar.gz ./LingmoSrcBuild/Deb

        - uses: actions/upload-artifact@v4
          with:
            name: LingmoOS Arm64 Built
            path: BuiltDeb.tar.gz
            compression-level: 9 # maximum compression