name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 59 59 23 * * ? *

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-data:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: | 
          JSON_OUTPUT=$(cat ${{ github.workspace }}/lingmo/pkgs | jq -R -s -c 'split("\n")[:-1] | map({pkg_name: .})')
          echo "matrix={\"pkgs\" : $JSON_OUTPUT}" >> $GITHUB_OUTPUT

  build:
    needs: generate-data
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie-slim
    strategy:
      matrix: ${{fromJson(needs.generate-data.outputs.matrix)}}
    name: Build ${{ matrix.pkgs.pkg_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Update Apt and Install packages
        run: |
          apt-get update -y && apt-get upgrade -y
          apt install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++ --no-install-recommends
          bash build-pkg.sh "${{ matrix.pkgs.pkg_name }}"
